# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Shell Tests
on:
  push:
    branches: [ dev/robgruen/electron_tests ]
  # schedule:
  #   - cron: "0 0 * * *"

permissions:
  id-token: write
  contents: read    

# run only one of these at a time
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build_ts:
    strategy:
      fail-fast: false
      matrix:
        #os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        os: ["windows-latest"]
        version: [18, 20, 22]
        exclude:
          # TODO: Test timeout jest work for some reason
          - os: windows-latest
            version: 22

    runs-on: ${{ matrix.os }}
    steps:
      - if: runner.os == 'Linux'
        run: |
          sudo apt install libsecret-1-0
      - name: Setup Git LF
        run: |
          git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ts:
              - "ts/**"
              - ".github/workflows/build-ts.yml"
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          package_json_file: ts/package.json
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
          cache: "pnpm"
          cache-dependency-path: ts/pnpm-lock.yaml          
      - name: Install dependencies (pnpm)
        working-directory: ts
        run: |
          pnpm install --frozen-lockfile --strict-peer-dependencies
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
        working-directory: ts/packages/shell
      - name: Build repo
        working-directory: ts
        run: |
          npm run build

      - name: Build Shell
        working-directory: ts/packages/shell
        run: |
          npm run build

      # - name: Test
      #   working-directory: ts
      #   run: |
      #     npm run test
      - name: Login to Azure
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5B0D2D6BA40F4710B45721D2112356DD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_39BB903136F14B6EAD8F53A8AB78E3AA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F36C1F2C4B2C49CA8DD5C52FAB98FA30 }}
      - name: Get Keys
        run: |
          node tools/scripts/getKeys.mjs
        working-directory: ts
      - name: Test CLI - verify .env & endpoint connectivity
        run: |
            npm run start:dev 'prompt' 'why is the sky blue'
        working-directory: ts/packages/cli      
      - name: Run shell
        run: |
            npm run shell
        working-directory: ts/packages/cli      
      - name: Shell Tests
        timeout-minutes: 180
        # run: |           
        #   working-directory: ts/packages/shell
        run: npx playwright test
        working-directory: ts/packages/shell
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: ts/packages/shell/test-results/
          overwrite: true
          retention-days: 30        
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ts/packages/shell/playwright-report/
          overwrite: true
          retention-days: 30


      # - name: Lint
      #   working-directory: ts
      #   run: |
      #     npm run lint
